name: CI

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  build-and-test:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Start and install PostgreSQL database
      run: sudo systemctl start postgresql.service && bash src/main/resources/database/install_database.sh
    - name: Compile app
      run: mvn compile
    - name: Run tests
      run: mvn test